2025-10-10 03:29:26 automatic update

diff --git a/.config/shell/functions b/.config/shell/functions
--- a/.config/shell/functions
+++ b/.config/shell/functions
@@ -1,6 +1,6 @@
 #!/bin/sh
 # -*- mode: sh; -*- vim: ft=sh:ts=2:sw=2:norl:et:
-# Time-stamp: <2025-08-29 18:11:46 cf>
+# Time-stamp: <2025-09-08 03:02:27 cf>
 #       _          _ _  __
 #   ___| |__   ___| | |/ _|_ __
 #  / __| '_ \ / _ \ | | |_| '_  \
@@ -2041,6 +2041,33 @@ esrt() {
            -map 0 -map 1 -c:v copy -c:a copy -c:s mov_text \
            -metadata:s:s:0 language="eng" "out.$x" || return 1
     return 0
+}
+
+addsv() {
+    [ $# -lt 1 ] && { echo "Usage: addsv <argsv>" >&2 ; return 1 ; }
+    svdir="/etc/runit/sv"
+    for sv in "$@" ; do
+        [ ! -d "${svdir}/${sv}" ] && { echo "Error: ${sv} doesn't exist in ${svdir}" >&2 ; continue ; }
+        [ ! -L "/run/runit/service/${sv}" ] && sudo ln -sf "${svdir}/${sv}" "/run/runit/service/${sv}"
+        sv status "$sv"
+    done
+    return 0
+}
+
+rmsv() {
+    [ $# -lt 1 ] && { echo "Usage: rmsv <argsv>" >&2 ; return 1 ; }
+    for sv in "$@" ; do
+        svlink="/run/runit/service/${sv}"
+        if [ -L "$svlink" ]; then
+            sudo sv stop "$sv"
+            sudo sv status "sv"
+            sudo unlink "$sv" && echo "${sv} service removed."
+        else
+            echo "Error: ${svlink} does not exist or is not a symbolic link." >&2
+        fi
+        continue
+    done
+    return
 }
 
 #  find_ytdirs_sort_prefix | while read -r d ; do
